### ISSUE TITLE
Changing number_of_hours does not clear cache

### ISSUE THREAD

**Issue by ThermIQ** [kotope/aio_energy_management#50] opened 2024-12-09 20:41 UTC
Connecting number_of_hours to an input_number for dynamic settings is suggested in the docs but you have to call the clear_data service in orde to recalculate the active number of hours.

**Comment by kotope** [comment] 2024-12-10 06:10
Hi!

That's by design. I don't want to update the data if it's already 'locked in' and variables changes.

Example:
- input_number is mapped to water heater amount and getting number of 6 hours for the night.
- at 21:00 I'll update the water heater to heat number_of_hours received from input_number
- water heater starts heating at cheapest hours, let say at 00:00
- at 01:00 number_of_hours is changed to 5 as water heater is heated sometime already.
- At this point, I don't want to interrupt the current schedule and recalculate everything as it would possibly ruin the water heating.

So after lock in the data won't be changed until expiration happens. If you want to update it during the schedule, you can always call the service clear_data to force recalculation :-)

I'll be closing this ticket. If you think this is still an issue or have a better approach, please open again or if you want to further discuss this, please open a thread on the discussions page :-)

**Closed by kotope** 2024-12-10 06:10 UTC

**Comment by ThermIQ** [comment] 2024-12-10 09:52
Thanks, It makes sense!
